
server:
  name: Template Integration Service
  host: localhost
  port: 8080
  writetimeout: 7
  readtimeout: 8

  adapter:
    url: /test
    login: login_test
    password: pass
    account: 123456
    timeout: 10

  agent:
    token: ""
    url: ""